(*
	В данном описании вместо конкретных значенй используются регулярные выражения.
	Это нужно для упрощения описания отдельных моментов, например наборов символов.
	Учитывайте данное обстоятельство при чтении описания.

*)

(* Упрощёный синтаксис для BASE *)

БлокКода = {СтрокаКода, {Пробел}, (ПереносСтроки | КонецТекста)};
СтрокаКода = Директива, {{ГраницаСлова}, РазделительДиректив, {ГраницаСлова}, Директива};
Директива = Оператор, [Выражение, {РазделительВыражений, {Пробел}, Выражение}],
			[ОтделительВложения, ВложенныйБлокКода] |
			Комментарий;
ВложенныйБлокКода = ОднострочныйБлокКода | МногострочныйБлокКода;
ОднострочныйБлокКода = СтрокаКода, {Пробел}, ПереносСтроки;
МногострочныйБлокКода = [Комментарий], ПереносСтроки,
						[БлокКода], КонецМногострочногоБлокаКода, {ПроизвольныйТекст},
						{{ГраницаСлова}, РазделительДиректив, {ГраницаСлова}, Директива},
						ПереносСтроки;
Комментарий = ОператорКомментария, ПроизвольныйТекст, (ПереносСтроки | КонецТекста)
Выражение = Значение {Операция, Значение}
Значение = Функция, ["(", [Выражение, {РазделительВыражений, {Пробел}, Выражение}], ")"] |
			"(", Выражение, ")" |
			Переменная | Число | СтрокаТекста

(* Операторы *)

Оператор = "\*PL" | "\*P" | НеявныйОператор | "ACT" | "LOOP" | "IF";
ОператорКомментария = "!";
КонецМногострочногоБлокаКода = "END";

(* Ограничители/Разделители *)

ГраницаСлова = Пробел | "\b";
Пробел = "\s" | "\t";
ПереносСтроки = "\n" | "\r" | "\r\n";
РазделительДиректив = "\&";
РазделительВыражений = ",";
ОтделительВложения = ":";
КонецТекста = ? Окончание файла ?;

(* Выражения и прочее *)

ПроизвольныйТекст = {"[\s\S]+"};
Переменная = "[^\W\d]\w*"
Число = "\d+"
СтрокаТекста = "'[\s\S]*'" | '"[\s\S]*"'
