(* Упрощёный синтаксис для BASE *)

(*
	В данном описании вместо конкретных значений используются регулярные выражения.
	Это нужно для упрощения описания отдельных моментов, например наборов символов.
	Учитывайте данное обстоятельство при чтении описания.

	В блоке BASE формата qsps (txt2gam) не допускаются пробелы перед именами ключевых
	операторов *PL, *P, ACT на верхнем уровне. Допускаются пробелы перед операторами
	во вложенных блоках кода, а так же между любыми сущностями.

	Сущности должны быть отделены друг от друга по границе слова, т.е. допустимо:
	*PL"string one"&*NL"string two"&!comment
*)

CodeBlock = {CodeLine, (NextLineSign | CodeEndSign)};
CodeLine = Directive, {DirectiveDelimiter, Directive};
Directive = Operator, [Expression, {ExpressionDelimiter, Expression}],
			[EmbeddingDelimiter, EmbeddedCode] |
			Variable {ExpressionDelimiter, Variable}, AsignmentOperator,
			Expression, {ExpressionDelimiter, Expression} |
			Comment;
EmbeddedCode = OneLineCode | ManyLinesCode;
OneLineCode = CodeLine, NextLineSign;
ManyLinesCode = [Comment], NextLineSign,
				[CodeBlock], ManyLinesCodeEnd, {AnyText},
				{DirectiveDelimiter, Directive}, NextLineSign;
Comment = CommentOperator, AnyText, (NextLineSign | CodeEndSign);
Expression = Value {Operation, Value};
Value = Function, ["(", [Expression, {ExpressionDelimiter, Expression}], ")"] |
			"(", Expression, ")" |
			Variable | Number | TextString;

(* Операторы *)

Operator = "\*PL" | "\*P" | ImplicitOperator | "ACT" | "LOOP" | "IF";
CommentOperator = "!";
ManyLinesCodeEnd = "END";

(* Ограничители/Разделители *)

WordEdge = SpaceSign | "\b";
SpaceSign = "\s" | "\t";
NextLineSign = "\n" | "\r" | "\r\n";
DirectiveDelimiter = "\&";
ExpressionDelimiter = ",";
EmbeddingDelimiter = ":";
CodeEndSign = ? End of File ?;

(* Выражения и прочее *)

AnyText = {"[\s\S]+"};
Variable = "[^\W\d]\w*";
Number = "\d+";
TextString = DoubleQuotedString | ApostrophedString | BraceCode;
AsignmentOperator = "=";
Operation = "\+" | "\-" | "\/" | "\*" | "or" | "and" | "mod" | ">=" | "<=" | ">" | "<" | "=";
ImplicitOperator = "(?=TextString)";
Function = "\$?func" | "\$?dyneval" | (* TODO: Добавить остальные функции *);
